datasets:
  - name: !class [EXAMPLE_db.EXAMPLE]
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        tmp: !pathjoin [data,tmp]
      subdb: normal
      filter:
        name: subsample
        method: random
        ratio: 0.5
      test_only: 0
  - name: !class [EXAMPLE_db.EXAMPLE]
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        tmp: !pathjoin [data,tmp]
      subdb: abnormal
      filter:
        name: subsample
        method: random
        ratio: 0.5
      test_only: 1
xval:
    name: sequential_random
    parameters:
      folds: 4
      val_frac: 0.3