datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        feat: !pathjoin [data,feat]
      subdb: normal
      split: 1 # split data in 1s segments
      test_only: 0
  - name: EXAMPLE
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        feat: !pathjoin [data,feat]
      subdb: abnormal
      split: 1 # split data in 1s segments
      test_only: 1