datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        feat: !pathjoin [data,feat]
      select:
        name: subsample_by_str
        parameters:
          key: [data,subdb]
          keep: normal
      test_only: 0
  - name: EXAMPLE
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        feat: !pathjoin [data,feat]
      select:
        name: subsample_by_str
        parameters:
          key: [data,subdb]
          keep: abnormal
      test_only: 1
select:
  name: random_subsample
  parameters:
    method: random
    ratio: 0.5