datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !pathjoin [data,data]
        meta: !pathjoin [data,data]
        tmp: !pathjoin [data,tmp]
xval:
    name: sequential_random
    parameters:
      folds: 4
      val_frac: 0.3