datasets:
  - name: DCASE2020Task1A
    parameters:
      paths:
        data: !kwarg [base_datasets,DCASE2020Task1A,data]
        meta: !kwarg [base_datasets,DCASE2020Task1A,meta]
        feat: !kwarg [base_datasets,DCASE2020Task1B,tmp]