datasets:
  - name: DCASE2020Task1B
    parameters:
      paths:
        data: !kwarg [base_datasets,DCASE2020Task1B,data]
        meta: !kwarg [base_datasets,DCASE2020Task1B,meta]
        feat: !kwarg [base_datasets,DCASE2020Task1B,feat]