datasets:
  - name: DCASE2020Task1B
    parameters:
      paths:
        data: !kwarg [base_datasets,DCASE2020Task1B,data]
        meta: !kwarg [base_datasets,DCASE2020Task1B,meta]
        tmp: !kwarg [tmp_folder]
xval:
    name: group_random
    parameters:
      folds: 4
      val_frac: 0.3
