chain:
  - name: Framing
    parameters:
      windowsize: 0.005
      stepsize: 0.0025
      axis: -1
  - name: FFT
    parameters:
      format: magnitude
  - name: Filterbank
    parameters:
      scale: linear
      n_bands: 16
  - name: Logarithm

