# base
base_data: &base_data \\Duke.edu.khk.be

# data sources (reference)
base_datasets:
    ISAAC_July2020_week1_Steel:
      data: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, Steel_week1, audio]
      meta: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, Steel_week1, meta]
      feat: !pathjoin [*base_data, JBOD2, ISAAC, features]
    ISAAC_July2020_week3_Steel:
      data: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, Steel_week3, audio]
      meta: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, Steel_week3, meta]
      feat: !pathjoin [*base_data, JBOD2, ISAAC, features]
    ISAAC_July2020_week2_SS316:
      data: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, SS316_week2, audio]
      meta: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, SS316_week2, meta]
      feat: !pathjoin [*base_data, JBOD2, ISAAC, features]
    ISAAC_July2020_week4_SS316:
      data: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, SS316_week4, audio]
      meta: !pathjoin [*base_data, JBOD2, ISAAC, ISAAC_July2020, week, SS316_week4, meta]
      feat: !pathjoin [*base_data, JBOD2, ISAAC, features]