input: data
output_target: binary_anomaly
test_metrics:
  - method: AUC
    input: binary_anomaly
modsel_metric: &modsel_metric mean_absolute_error
keras:
  batch_size: 3
  epochs: 20
  compile:
    loss: mean_absolute_error
    metrics: [mean_absolute_error]
    optimizer:
      method: Adam
      param:
        lr: 0.001
  callbacks:
    - ModelCheckpoint_custom:
        filepath: !kwarg [filepath_mcpcb]
        period: 5
        save_best_only: True
        save_weights_only: True
        mode: min
        monitor: !join [val_, *modsel_metric]
data_generator:
  subsampling:
    method: random
    ratio: 1