datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !kwarg [base_datasets,EXAMPLE,data]
        meta: !kwarg [base_datasets,EXAMPLE,meta]
        feat: !kwarg [base_datasets,EXAMPLE,feat]
      subdb: normal
      split: 10 # split data in 10s segments
      test_only: 0
  - name: EXAMPLE
    parameters:
      paths:
        data: !kwarg [base_datasets,EXAMPLE,data]
        meta: !kwarg [base_datasets,EXAMPLE,meta]
        feat: !kwarg [base_datasets,EXAMPLE,feat]
      subdb: abnormal
      split: 10 # split data in 10s segments
      test_only: 1
xval:
    name: random
    parameters:
      folds: 4
      val_frac: 0.3