datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !kwarg [base_datasets,EXAMPLE,data]
        meta: !kwarg [base_datasets,EXAMPLE,meta]
      subdb: normal
      test_only: 0
  - name: EXAMPLE
    parameters:
      paths:
        data: !kwarg [base_datasets,EXAMPLE,data]
        meta: !kwarg [base_datasets,EXAMPLE,meta]
      subdb: abnormal
      test_only: 1
xval:
    name: random
    parameters:
      folds: 4
      val_frac: 0.3
