datasets:
  - name: EXAMPLE
    parameters:
      paths:
        data: !kwarg [base_datasets,EXAMPLE,data]
        meta: !kwarg [base_datasets,EXAMPLE,meta]
        feat: !kwarg [base_datasets,EXAMPLE,feat]
      subdb: normal






