chain:
  - name: Framing
    parameters:
      windowsize: 0.040
      stepsize: 0.020
      axis: -1
  - name: FFT
    parameters:
      format: magnitude
  - name: Filterbank
    parameters:
      scale: mel
      n_bands: 40
  - name: Logarithm


