# base
base_data: &base_data data

# data sources (reference)
base_datasets:
    DCASE2020Task1B:
      data: !pathjoin [*base_data, DCASE2020,datasets,TAU-urban-acoustic-scenes-2020-3class-development,audio]
      meta: !pathjoin [*base_data, DCASE2020,datasets,TAU-urban-acoustic-scenes-2020-3class-development]
      feat: !pathjoin [*base_data, DCASE2020,features]
    DCASE2020Task1A:
      data: !pathjoin [*base_data, DCASE2020,datasets,TAU-urban-acoustic-scenes-2020-mobile-development,audio]
      meta: !pathjoin [*base_data, DCASE2020,datasets,TAU-urban-acoustic-scenes-2020-mobile-development]
      feat: !pathjoin [*base_data, DCASE2020,features]

