datasets:
  - name: ISAAC_SS316
    parameters:
      paths:
        data: !kwarg [base_datasets,ISAAC_SS316,data]
        meta: !kwarg [base_datasets,ISAAC_SS316,meta]
        feat: !kwarg [base_datasets,ISAAC_SS316,feat]
      sensor: piezo
      subdb: [None_f, 0uA_f, 10uA_f, 100uA_f, 1mA_f]